blank_issues_enabled: false
contact_links:
  - name: Dúvidas gerais
    url: https://github.com/savio04/extenso-ptbr/discussions
    about: Para perguntas sobre uso da biblioteca, use as Discussions.
